import { createEnv } from '@t3-oss/env-core';
import { z } from 'zod';

export const environment = createEnv({
	server: {
		BETTER_AUTH_URL: z.string().url().optional(),
		BETTER_AUTH_SECRET: z.string().min(32),
		GOOGLE_CLIENT_ID: z.string().min(1),
		GOOGLE_CLIENT_SECRET: z.string().min(1),
		REDIS_URL: z.string().url(),
		RATE_LIMIT_REGISTER_MAX: z.coerce.number().int().positive().default(10),
		RATE_LIMIT_REGISTER_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
		RATE_LIMIT_TOKEN_MAX: z.coerce.number().int().positive().default(30),
		RATE_LIMIT_TOKEN_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
		INSTANCE_IDENTIFIER: z.string().optional(),
		RAILWAY_REPLICA_IDENTIFIER: z.string().optional(),
		HOSTNAME_IDENTIFIER: z.string().optional(),
		MCP_PROTOCOL_VERSION: z.literal('2025-11-25').optional().default('2025-11-25'),
		MCP_ALLOWED_ORIGINS: z.string().min(1),
		MCP_ENABLE_UI_EXTENSION: z.coerce.boolean().optional().default(true),
		MCP_ENABLE_CLIENT_CREDENTIALS: z.coerce.boolean().optional().default(true),
		MCP_ENABLE_ENTERPRISE_AUTH: z.coerce.boolean().optional().default(true),
		MCP_CONFORMANCE_MODE: z.coerce.boolean().optional().default(false),
		ENTERPRISE_AUTH_PROVIDER_URL: z.string().url().optional(),
		ENTERPRISE_AUTH_TENANT: z.string().optional(),
		ENTERPRISE_AUTH_AUDIENCE: z.string().optional(),
		ENTERPRISE_AUTH_CLIENT_ID: z.string().optional(),
		ENTERPRISE_AUTH_CLIENT_SECRET: z.string().optional(),
		ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS: z.string().optional(),
	},
	runtimeEnv: {
		BETTER_AUTH_URL: process.env.BETTER_AUTH_URL
			? process.env.BETTER_AUTH_URL
			: process.env.RAILWAY_PUBLIC_DOMAIN
				? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}`
				: undefined,
		BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
		GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
		GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
		REDIS_URL: process.env.REDIS_URL,
		RATE_LIMIT_REGISTER_MAX: process.env.RATE_LIMIT_REGISTER_MAX,
		RATE_LIMIT_REGISTER_WINDOW_SECONDS: process.env.RATE_LIMIT_REGISTER_WINDOW_SECONDS,
		RATE_LIMIT_TOKEN_MAX: process.env.RATE_LIMIT_TOKEN_MAX,
		RATE_LIMIT_TOKEN_WINDOW_SECONDS: process.env.RATE_LIMIT_TOKEN_WINDOW_SECONDS,
		INSTANCE_IDENTIFIER: process.env.INSTANCE_IDENTIFIER,
		RAILWAY_REPLICA_IDENTIFIER: process.env.RAILWAY_REPLICA_ID ?? process.env.RAILWAY_INSTANCE_ID,
		HOSTNAME_IDENTIFIER: process.env.HOSTNAME,
		MCP_PROTOCOL_VERSION: process.env.MCP_PROTOCOL_VERSION,
		MCP_ALLOWED_ORIGINS: process.env.MCP_ALLOWED_ORIGINS,
		MCP_ENABLE_UI_EXTENSION: process.env.MCP_ENABLE_UI_EXTENSION,
		MCP_ENABLE_CLIENT_CREDENTIALS: process.env.MCP_ENABLE_CLIENT_CREDENTIALS,
		MCP_ENABLE_ENTERPRISE_AUTH: process.env.MCP_ENABLE_ENTERPRISE_AUTH,
		MCP_CONFORMANCE_MODE: process.env.MCP_CONFORMANCE_MODE,
		ENTERPRISE_AUTH_PROVIDER_URL: process.env.ENTERPRISE_AUTH_PROVIDER_URL,
		ENTERPRISE_AUTH_TENANT: process.env.ENTERPRISE_AUTH_TENANT,
		ENTERPRISE_AUTH_AUDIENCE: process.env.ENTERPRISE_AUTH_AUDIENCE,
		ENTERPRISE_AUTH_CLIENT_ID: process.env.ENTERPRISE_AUTH_CLIENT_ID,
		ENTERPRISE_AUTH_CLIENT_SECRET: process.env.ENTERPRISE_AUTH_CLIENT_SECRET,
		ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS: process.env.ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS,
	},
	emptyStringAsUndefined: true,
	skipValidation: process.env.SKIP_ENV_VALIDATION === 'true',
});
