import { createEnv } from '@t3-oss/env-core';
import { z } from 'zod';

export const environment = createEnv({
	server: {
		BASE_URL: z.string().url().optional(),
		SESSION_SIGNING_SECRET: z.string().min(32),
		GOOGLE_CLIENT_ID: z.string().min(1),
		GOOGLE_CLIENT_SECRET: z.string().min(1),
		SESSION_COOKIE_NAME: z.string().min(1).optional().default('application_session'),
		SESSION_TIME_TO_LIVE_SECONDS: z.coerce.number().int().positive().optional().default(2_592_000),
		REDIS_URL: z.string().url(),
		RATE_LIMIT_REGISTER_MAX: z.coerce.number().int().positive().default(10),
		RATE_LIMIT_REGISTER_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
		RATE_LIMIT_TOKEN_MAX: z.coerce.number().int().positive().default(30),
		RATE_LIMIT_TOKEN_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
		INSTANCE_IDENTIFIER: z.string().optional(),
		RAILWAY_REPLICA_IDENTIFIER: z.string().optional(),
		HOSTNAME_IDENTIFIER: z.string().optional(),
		MCP_PROTOCOL_VERSION: z.literal('2025-11-25').optional().default('2025-11-25'),
		MCP_ALLOWED_ORIGINS: z.string().min(1),
		MCP_ENABLE_UI_EXTENSION: z.coerce.boolean().optional().default(true),
		MCP_ENABLE_CLIENT_CREDENTIALS: z.coerce.boolean().optional().default(true),
		MCP_ENABLE_ENTERPRISE_AUTH: z.coerce.boolean().optional().default(true),
		MCP_CONFORMANCE_MODE: z.coerce.boolean().optional().default(false),
		MCP_TOKEN_TTL_SECONDS: z.coerce.number().positive().optional().default(3600),
		MCP_REFRESH_TOKEN_TTL_SECONDS: z.coerce.number().positive().optional().default(2592000),
		RATE_LIMIT_MCP_MAX: z.coerce.number().int().positive().default(60),
		RATE_LIMIT_MCP_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
		ENTERPRISE_AUTH_PROVIDER_URL: z.string().url().optional(),
		ENTERPRISE_AUTH_TENANT: z.string().optional(),
		ENTERPRISE_AUTH_AUDIENCE: z.string().optional(),
		ENTERPRISE_AUTH_CLIENT_ID: z.string().optional(),
		ENTERPRISE_AUTH_CLIENT_SECRET: z.string().optional(),
		ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS: z.string().optional(),
		PORT: z.coerce.number().int().positive().optional().default(3000),
		NODE_ENV: z.enum(['development', 'production', 'test']).optional().default('development'),
	},
	runtimeEnv: {
		BASE_URL: process.env.BASE_URL,
		SESSION_SIGNING_SECRET: process.env.SESSION_SIGNING_SECRET,
		GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
		GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
		SESSION_COOKIE_NAME: process.env.SESSION_COOKIE_NAME,
		SESSION_TIME_TO_LIVE_SECONDS: process.env.SESSION_TIME_TO_LIVE_SECONDS,
		REDIS_URL: process.env.REDIS_URL,
		RATE_LIMIT_REGISTER_MAX: process.env.RATE_LIMIT_REGISTER_MAX,
		RATE_LIMIT_REGISTER_WINDOW_SECONDS: process.env.RATE_LIMIT_REGISTER_WINDOW_SECONDS,
		RATE_LIMIT_TOKEN_MAX: process.env.RATE_LIMIT_TOKEN_MAX,
		RATE_LIMIT_TOKEN_WINDOW_SECONDS: process.env.RATE_LIMIT_TOKEN_WINDOW_SECONDS,
		INSTANCE_IDENTIFIER: process.env.INSTANCE_IDENTIFIER,
		RAILWAY_REPLICA_IDENTIFIER: process.env.RAILWAY_REPLICA_ID ?? process.env.RAILWAY_INSTANCE_ID,
		HOSTNAME_IDENTIFIER: process.env.HOSTNAME,
		MCP_PROTOCOL_VERSION: process.env.MCP_PROTOCOL_VERSION,
		MCP_ALLOWED_ORIGINS: process.env.MCP_ALLOWED_ORIGINS,
		MCP_ENABLE_UI_EXTENSION: process.env.MCP_ENABLE_UI_EXTENSION,
		MCP_ENABLE_CLIENT_CREDENTIALS: process.env.MCP_ENABLE_CLIENT_CREDENTIALS,
		MCP_ENABLE_ENTERPRISE_AUTH: process.env.MCP_ENABLE_ENTERPRISE_AUTH,
		MCP_CONFORMANCE_MODE: process.env.MCP_CONFORMANCE_MODE,
		MCP_TOKEN_TTL_SECONDS: process.env.MCP_TOKEN_TTL_SECONDS,
		MCP_REFRESH_TOKEN_TTL_SECONDS: process.env.MCP_REFRESH_TOKEN_TTL_SECONDS,
		RATE_LIMIT_MCP_MAX: process.env.RATE_LIMIT_MCP_MAX,
		RATE_LIMIT_MCP_WINDOW_SECONDS: process.env.RATE_LIMIT_MCP_WINDOW_SECONDS,
		ENTERPRISE_AUTH_PROVIDER_URL: process.env.ENTERPRISE_AUTH_PROVIDER_URL,
		ENTERPRISE_AUTH_TENANT: process.env.ENTERPRISE_AUTH_TENANT,
		ENTERPRISE_AUTH_AUDIENCE: process.env.ENTERPRISE_AUTH_AUDIENCE,
		ENTERPRISE_AUTH_CLIENT_ID: process.env.ENTERPRISE_AUTH_CLIENT_ID,
		ENTERPRISE_AUTH_CLIENT_SECRET: process.env.ENTERPRISE_AUTH_CLIENT_SECRET,
		ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS: process.env.ENTERPRISE_AUTH_ALLOWED_CLIENT_IDS,
		PORT: process.env.PORT,
		NODE_ENV: process.env.NODE_ENV as 'development' | 'production' | 'test' | undefined,
	},
	emptyStringAsUndefined: true,
	skipValidation: process.env.SKIP_ENV_VALIDATION === 'true',
});
